// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJbMhZJBERkwoGKQ9h3MmuhPpsRwfpIV8',
    appId: '1:251065056372:web:3b9dec7cd8df07a122e521',
    messagingSenderId: '251065056372',
    projectId: 'admins-app-d6190',
    authDomain: 'admins-app-d6190.firebaseapp.com',
    storageBucket: 'admins-app-d6190.appspot.com',
    measurementId: 'G-CPYN8NS85Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeLMoyY9Raf9cjofXXIQB08ozFkuFNSsk',
    appId: '1:251065056372:android:eb9ddfd22411b90322e521',
    messagingSenderId: '251065056372',
    projectId: 'admins-app-d6190',
    storageBucket: 'admins-app-d6190.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiPkmv8dTwEAMIGSo7zHQ5zGSMOe5r9Ok',
    appId: '1:251065056372:ios:8960bd280fe9b5cc22e521',
    messagingSenderId: '251065056372',
    projectId: 'admins-app-d6190',
    storageBucket: 'admins-app-d6190.appspot.com',
    iosBundleId: 'com.example.adminApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiPkmv8dTwEAMIGSo7zHQ5zGSMOe5r9Ok',
    appId: '1:251065056372:ios:b4b5e32d208f15ad22e521',
    messagingSenderId: '251065056372',
    projectId: 'admins-app-d6190',
    storageBucket: 'admins-app-d6190.appspot.com',
    iosBundleId: 'com.example.adminApp.RunnerTests',
  );
}
